# Generated by Django 4.2.23 on 2025-07-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dob', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=150)),
                ('user_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('created_on', models.CharField(max_length=30)),
            ],
        ),
    ]
